# named volume 'portainer_data' is marked as "external" (used by service 'portainer-ce'), so either remove "external" from volume definition or it needs to be created using: docker volume create portainer_data
name: porteiner
services:
    portainer-ce:
        ports:
            - 8000:8000
            - 9443:9443
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        image: portainer/portainer-ce:lts
volumes:
    portainer_data:
        external: true
        name: portainer_data
